x = input()
if x == 'NLCS': print('North London Collegiate School')
elif x == 'BHA': print('Branksome Hall Asia')
elif x == 'KIS': print('Korea International School')
else: print('St. Johnsbury Academy')